---
title: "Relatório de votos"
author: "Pedro Ruas"
date: "`r Sys.Date()`"
output: html_document
---

```{r, include=FALSE}

library(rmarkdown)
library(tidyverse)
library(plotly)
library(sf)

```
```{r, include=FALSE}

votos_bairros_du_20 <- readRDS("~/votos_bairros_duarte.rds")


```

```{r, include=FALSE}
mapa_ggplot_20 <- ggplot() +
  geom_sf(data = votos_bairros_du_20, aes(fill = total_votos, text = paste("Bairro:", name_neighborhood, "<br>Votos:", total_votos)), 
          color = "black", alpha = 0.7) +
  scale_fill_viridis_c(option = "viridis", direction = -1, na.value = "white", name = "Votos") +
  ggtitle("Distribuição de votos por bairro no Rio de Janeiro") +
   theme_classic() + # Usando um tema com controle mais flexível
  theme(
    plot.title = element_text(hjust = 0.5, vjust = 1, margin = margin(b = 10)) # Ajustando posição do título
  )

```

```{r, include=FALSE}
# Tornar interativo com plotly
mapa_interativo_du_20 <- ggplotly(mapa_ggplot_20, tooltip = "text")

```
## Desempenho Pedro Duarte 2020
### Mapa interativo
```{r, echo=FALSE}

mapa_interativo_du_20

```
## Tabela de Dados
```{r, echo=FALSE}
#Pedro Duarte 2020
du_20_votos_bairros <- votos_bairros_du_20 %>% 
  dplyr::select(Candidato = NM_VOTAVEL, Votos = total_votos, Bairro = name_neighborhood) %>% st_drop_geometry()

  
du_20_votos_bairros <- dplyr::arrange(du_20_votos_bairros, desc(Votos), .by_group = TRUE)
  
paged_table(du_20_votos_bairros)

```
## Total de votos

### 10069
```{r, include=FALSE}

D20 <- sum(du_20_votos_bairros$Votos)

D20

```

```{r, include=FALSE}

#Pedro Duarte 2024

votos_bairros <- readRDS("~/votos_bairros.rds")


```

```{r, include=FALSE}

# Seu gráfico ggplot
mapa_ggplot <- ggplot() +
  geom_sf(data = votos_bairros, aes(fill = total_votos, text = paste("Bairro:", name_neighborhood, "<br>Votos:", total_votos)), 
          color = "black", alpha = 0.7) +
  scale_fill_viridis_c(option = "viridis", direction = -1, na.value = "white", name = "Votos") +
  ggtitle("Distribuição de votos por bairro no Rio de Janeiro") +
   theme_classic() + # Usando um tema com controle mais flexível
  theme(
    plot.title = element_text(hjust = 0.5, vjust = 1, margin = margin(b = 10)) # Ajustando posição do título
  )
```


```{r, include=FALSE}
# Tornar interativo com plotly
mapa_interativo <- ggplotly(mapa_ggplot, tooltip = "text")

```

# Desempenho Pedro Duarte 2024
### Mapa Interativo

```{r, echo=FALSE}

mapa_interativo

```
## Tabela de Dados
```{r, echo=FALSE}

Duarte_votos_bairros <- votos_bairros %>% 
  dplyr::select(Candidato = NM_VOTAVEL, Votos = total_votos, Bairro = name_neighborhood) %>% st_drop_geometry()

  
Duarte_votos_bairros <- dplyr::arrange(Duarte_votos_bairros, desc(Votos), .by_group = TRUE)
  
paged_table(Duarte_votos_bairros)

```

## Total de votos

### 15404

```{r, echo=FALSE}

D24 <- sum(Duarte_votos_bairros$Votos)

D24

```

